export class Actions {

  static SIDEMENUTOGGLE="SIDEMENUTOGGLE"; 
  static SCREENRESIZE="SCREENRESIZE";
  static THEMESWITCHER="THEMESWITCHER";

  //player actions
  static PLAYPAUSETOGGLE="PLAYPAUSETOGGLE";
  static PLAYLISTTOGGLE="PLAYLISTTOGGLE";
  static PLAYERMUTETOGGLE="PLAYERMUTETOGGLE";

  
  
	constructor(){
		
	}  


}
